build:
  environment:
    node: '8.9.4'
  tests:
    override:
      - command: 'npm test'
        coverage:
          file: 'coverage/clover.xml'
          format: 'clover'
checks:
  javascript:
    code_rating: true

filter:
  excluded_paths:
    - "*.min.js" # Don't analyze minified files
